const address="東京都葛飾区奥戸3丁目25-14";const originCoord="35.732025,139.863983";
const stops={"五丁目住宅":{image:"assets/route-gochome.svg",bbox:"139.859610,35.729030,139.868610,35.735030",coord:"35.732030,139.864110",walk:1,q:"五丁目住宅 バス停 東京都葛飾区奥戸",note:"院を出てすぐの最寄り停留所です。道路を渡る前に、行き先と停留所標識の方面を確認してください。",marks:["鈴木接骨院・ドルフィンはりきゅう院","五丁目住宅バス停"],official:"https://transfer-cloud.navitime.biz/keiseibus-group/courses?busstop=00020473"},"奥戸3丁目":{image:"assets/route-okudo3.svg",bbox:"139.857690,35.731475,139.866690,35.737475",coord:"35.734475,139.862190",walk:5,q:"奥戸三丁目 バス停 京成バス 東京都葛飾区",note:"五丁目住宅付近から奥戸四丁目側へ進みます。青い徒歩経路に沿ってください。",marks:["五丁目住宅バス停","奥戸四丁目","奥戸三丁目バス停"],official:"https://transfer-cloud.navitime.biz/keiseibus-group/courses?busstop=00020384"},"奥戸6丁目":{image:"assets/route-okudo6.svg",bbox:"139.863598,35.728575,139.872598,35.734575",coord:"35.731575,139.868098",walk:6,q:"奥戸六丁目 バス停 京成バス 東京都葛飾区",note:"同名停留所が道路の両側にあるため、乗る駅方面を必ず確認してください。",marks:["五丁目住宅バス停","奥戸六丁目バス停","北沼公園方面"],official:"https://transfer-cloud.navitime.biz/keiseibus-group/"}};
const destinations=["金町駅","亀有駅","青砥駅","小岩駅","京成小岩駅","新小岩駅"];
const routes=[["奥戸3丁目","金町駅",22,8,42],["奥戸3丁目","亀有駅",20,17,31],["奥戸3丁目","青砥駅",15,25,45],["奥戸6丁目","亀有駅",18,6,29],["奥戸6丁目","小岩駅",17,13,26],["奥戸6丁目","京成小岩駅",15,21,38],["五丁目住宅","亀有駅",24,2,35],["五丁目住宅","新小岩駅",16,11,19],["五丁目住宅","青砥駅",18,28,47]];
let selected="金町駅",mode="all",mapStop="五丁目住宅";const $=id=>document.getElementById(id);const enc=encodeURIComponent;const clock=m=>`${String(Math.floor(m/60)%24).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
function drawMap(){const s=stops[mapStop];$("map").src=`map.html?stop=${enc(mapStop)}&v=20260719-2`;$("mapTitle").textContent=`${mapStop}バス停`;$("mapNote").textContent=s.note;$("landmarks").innerHTML=`<b>地図で見る目印</b>${s.marks.map((x,i)=>`<div class="landmark"><span>${i+1}</span>${x}</div>`).join("")}`;$("googleRoute").href=`https://www.google.com/maps/dir/?api=1&origin=${originCoord}&destination=${s.coord}&travelmode=walking`;$("currentRoute").href=`https://www.google.com/maps/dir/?api=1&destination=${s.coord}&travelmode=walking`;$("mapTabs").innerHTML=Object.entries(stops).map(([n,v])=>`<button class="map-tab ${n===mapStop?"active":""}" data-stop="${n}"><span>${n}</span><b>約 ${v.walk}分</b></button>`).join("");document.querySelectorAll("[data-stop]").forEach(b=>b.onclick=()=>{mapStop=b.dataset.stop;drawMap()})}
function drawControls(){$("destinations").innerHTML=destinations.map(d=>`<button class="destination ${d===selected?"active":""}" data-d="${d}">${d===selected?"✓ ":""}${d}</button>`).join("");document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{selected=b.dataset.d;mode="one";drawControls();drawResults()});$("oneLabel").textContent=`${selected}だけ見る`;$("walks").innerHTML=Object.entries(stops).map(([n,s])=>`<div class="walk">🚶 ${n}<strong>${s.walk}分</strong></div>`).join("")}
function drawResults(){const now=new Date(),mins=now.getHours()*60+now.getMinutes();$("now").textContent=`現在 ${clock(mins)}`;$("resultTime").textContent=clock(mins);$("resultTitle").textContent=mode==="all"?"早く着くバス":`${selected}へ行くバス`;const rs=routes.filter(r=>mode==="all"||r[1]===selected).map(r=>{const [stop,dest,ride,off,every]=r,w=stops[stop].walk,safe=mins+w+3,dep=safe+((off-safe%every+every)%every);return{stop,dest,w,dep,arr:dep+ride,wait:dep-mins}}).sort((a,b)=>a.arr-b.arr).slice(0,6);$("results").innerHTML=rs.length?rs.map((r,i)=>`<article class="bus ${i===0?"best":""}"><div><div class="bus-route">${r.stop} → ${r.dest}</div><div class="arrival">${clock(r.arr)}<small>駅に到着予定</small></div><div class="details">🚶 徒歩 ${r.w}分　🚌 ${clock(r.dep)} 発</div></div><div class="count">あと <b>${r.wait}</b>分</div><a class="official" href="${stops[r.stop].official}" target="_blank">公式時刻表 ↗</a></article>`).join(""):"<p>この行き先の候補便はありません。</p>"}
$("one").onclick=()=>{mode="one";drawResults()};$("all").onclick=()=>{mode="all";drawResults()};drawMap();drawControls();drawResults();setInterval(drawResults,30000);
